### ISSUE TITLE
crash with version 1.11

### ISSUE THREAD

**Issue by kzintiwife** [Ch1a/FlatWorld#1]
forge 13.20.0.2227
it was pointed out on the forge forums that flat world was the problem.  - http://www.minecraftforge.net/forum/topic/49319-crash-on-destroying-stone-in-mc-1112/#comment-249012

I've been using flatworld (https://minecraft.curseforge.com/projects/flatworld?gameCategorySlug=mc-mods&projectID=254472) to fast dig. It pops a bunch of blocks at once.

I have an auto sort on a backpack set (https://minecraft.curseforge.com/projects/backpacks?gameCategorySlug=mc-mods&projectID=223957) to pick up cobble and dirt.

sometimes when using the flat tool i get the following crash report.
first line of error (for searching):

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, granite, smooth_granite, diorite, smooth_diorite, andesite, smooth_andesite]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]} 

[crash-2017-02-11_12.12.10-client.txt](https://github.com/Ch1a/FlatWorld/files/768878/crash-2017-02-11_12.12.10-client.txt)

These lines
    at net.minecraft.block.Block.func_180653_a(Block.java:557)
    at net.minecraft.block.Block.func_176226_b(Block.java:550)
    at com.ch1a.flatworld.ItemFlattening.itemDrop(ItemFlattening.java:144)
    at com.ch1a.flatworld.ItemFlattening.checkDropItem(ItemFlattening.java:135)

**Comment by kzintiwife** [comment]
Wow. thanks for the quick address of the issue :) 👍

**Comment by kzintiwife** [comment]
after update - still do the crash. 
new crash reports. 

[crash-2017-02-11_23.21.31-client.txt](https://github.com/Ch1a/FlatWorld/files/769118/crash-2017-02-11_23.21.31-client.txt)

**Comment by kzintiwife** [comment]
looks like the crash if from very fast and repeated calls to the on-the-fly configuration file.
